### ISSUE TITLE
Validation type - should have been 'object' but was 'Array'.

### ISSUE THREAD

**Issue by photkey** [dalyIsaac/Whim#1099]
https://dalyisaac.github.io/Whim/configure/core/workspaces.html
```
workspaces:
  entries:
    - name: Browser
      layout_engines:
        - type: SliceLayoutEngine
          variant:
            type: column
        - type: SliceLayoutEngine
          variant:
            type: row
        - type: TreeLayoutEngine

    - name: IDE
    - name: Chat
    - name: Spotify
    - name: Other
```

Adding the example configuration from the official documentation to the config file resulted in an error. The error message is:
```
Error 1:
Validation type - should have been 'object' but was 'Array'.
Violated #/properties/workspaces/properties/entries/items/$ref/properties/layout_engines/$ref/type
```
