### ISSUE TITLE
Windows key (RWin and LWin) interference with Windows built in keyboard shortcuts

### ISSUE THREAD

**Issue by CaMeLCaseError** [dalyIsaac/Whim#1120]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Behavior

As an example: mapping RWin+2 to switch to Workspace2 would be a very popular mapping.

Expected Behaviour:
Pressing RWin+2 goes to Workspace2 on the current Monitor.

Actual Behaviour: 
Rwin+2 opens a Microsoft Edge browser (built in Browser)
Repeated Press of RWin+2: Switches to Workspace2 (Windows detects that Edge is already running)

### C# Config

```csharp
#nullable enable
#r "C:\Program Files\Whim\whim.dll"
#r "C:\Program Files\Whim\plugins\Whim.Bar\Whim.Bar.dll"
#r "C:\Program Files\Whim\plugins\Whim.CommandPalette\Whim.CommandPalette.dll"
#r "C:\Program Files\Whim\plugins\Whim.FloatingWindow\Whim.FloatingWindow.dll"
#r "C:\Program Files\Whim\plugins\Whim.FocusIndicator\Whim.FocusIndicator.dll"
#r "C:\Program Files\Whim\plugins\Whim.Gaps\Whim.Gaps.dll"
#r "C:\Program Files\Whim\plugins\Whim.LayoutPreview\Whim.LayoutPreview.dll"
#r "C:\Program Files\Whim\plugins\Whim.SliceLayout\Whim.SliceLayout.dll"
#r "C:\Program Files\Whim\plugins\Whim.TreeLayout\Whim.TreeLayout.dll"
#r "C:\Program Files\Whim\plugins\Whim.TreeLayout.Bar\Whim.TreeLayout.Bar.dll"
#r "C:\Program Files\Whim\plugins\Whim.TreeLayout.CommandPalette\Whim.TreeLayout.CommandPalette.dll"
#r "C:\Program Files\Whim\plugins\Whim.Updater\Whim.Updater.dll"
#r "C:\Program Files\Whim\plugins\Whim.Yaml\Whim.Yaml.dll"

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Microsoft.UI;
using Microsoft.UI.Xaml.Markup;
using Microsoft.UI.Xaml.Media;
using Whim;
using Whim.Bar;
using Whim.CommandPalette;
using Whim.FloatingWindow;
using Whim.FocusIndicator;
using Whim.Gaps;
using Whim.LayoutPreview;
using Whim.SliceLayout;
using Whim.TreeLayout;
using Whim.TreeLayout.Bar;
using Whim.TreeLayout.CommandPalette;
using Whim.Updater;
using Whim.Yaml;
using Windows.Win32.UI.Input.KeyboardAndMouse;

/// <summary>
/// This is what's called when Whim is loaded.
/// </summary>
/// <param name="context"></param>
void DoConfig(IContext context)
{
	context.Logger.Config = new LoggerConfig();

	// YAML config. It's best to load this first so that you can use it in your C# config.
	YamlLoader.Load(context);

	// Customize your config in C# here.
	// For more, see https://dalyisaac.github.io/Whim/script/scripting.html
	// ...
}

// We return doConfig here so that Whim can call it when it loads.
return DoConfig;
```

### YAML Config

```yaml
# yaml-language-server: $schema=C:\Program Files\Whim\plugins\Whim.Yaml\schema.json
workspaces:
  entries:
    - name: Workspace 1
    - name: Workspace 2
    - name: Workspace 3
    - name: Workspace Q
    - name: Workspace W
    - name: Workspace E

layout_engines:
  entries:
    - type: tree
      initial_direction: right

    - type: slice
      variant:
        type: row

    - type: slice
      variant:
        type: column

    - type: slice
      variant:
        type: primary_stack

    - type: slice
      variant:
        type: secondary_primary_stack

    - type: slice
      variant:
        type: multi_column_stack
        columns: [2, 1, 0]

    - type: slice
      variant:
        type: secondary_primary_stack
        primary_capacity: 1
        secondary_capacity: 2

    - type: focus
      maximize: false

    - type: floating

keybinds:
  entries:
    - command: whim.core.focus_next_monitor
      keybind: LCtrl+LShift+LAlt+K

    - command: whim.core.focus_previous_monitor
      keybind: LCtrl+LShift+LAlt+J

    - command: whim.core.activate_workspace_1
      keybind: RWin+1

    - command: whim.core.activate_workspace_2
      keybind: RWin+2

    - command: whim.core.activate_workspace_3
      keybind: RWin+3
    
    - command: whim.core.activate_workspace_4
      keybind: RWin+Q

    - command: whim.core.activate_workspace_5
      keybind: RWin+W
     
    - command: whim.core.activate_workspace_6
      keybind: RWin+E

    - command: whim.core.move_window_to_next_monitor
      keybind: LCtrl+LShift+Right

    - command: whim.core.move_window_to_previous_monitor
      keybind: LCtrl+LShift+Left

    - command: whim.core.cycle_layout_engine
      keybind: LCtrl+LShift+Space

filters:
  entries: []

routers:
  routing_behavior: route_to_launched_workspace

plugins:
  bar:
    left_components:
      entries:
        - type: workspace_widget

    center_components:
      entries:
        - type: focused_window_widget
          shorten_title: true

    right_components:
      entries:
        - type: battery_widget
        - type: active_layout_widget
        - type: date_time_widget
          format: HH:mm:ss, dd MMM yyyy
        - type: tree_layout_widget

  floating_window:
    is_enabled: true

  gaps:
    is_enabled: true
    outer_gap: 2
    inner_gap: 2
    default_outer_delta: 2
    default_inner_delta: 2

  command_palette:
    is_enabled: true
    max_height_percent: 40
    max_width_pixels: 800
    y_position_percent: 20

  focus_indicator:
    is_enabled: true
    border_size: 3
    is_fade_enabled: false
    fade_timeout: 2
    color: red

  layout_preview:
    is_enabled: true

  updater:
    is_enabled: true
    release_channel: alpha
    update_frequency: monthly
```

### Environment

- Windows: Windows 11 Pro (24H2)
- Architecture: x86_64
- Fresh install of WhimInstaller-x64-0.7.62-alpha+ee39f519.ee39f519a01e3021de05b4698af49b28f8530f37

### Steps To Reproduce

Steps to Reproduce:
make a mapping using RWin+"AnyKey"
press Rwin+AnyKey

### Anything else?

Suggestions to fix:
Autohotkey V2 has solved this problem and also is offering a way to remap key combinations which are occupied by Wndows built in shortcuts. Some possible solutions:
- make it possible to use Autohotkey to control Whim (e.g. done in komorebi)
- use the same method for grabbing already used Keyboard that Autohotkey uses.

Workaround:
Remap Key Combinations in Autohotkey V2 to unique Combinations which aren't used already by Windows and use them inside Whim.
